global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'data_preprocessor'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8050']

  - job_name: 'triton'
    metrics_path: /metrics
    static_configs:
      - targets: ['triton:8002']
