version: "3.9"
services:
  preprocess:
    build: ./preprocess
    ports:
      - "5001:5000"
    depends_on:
      - model
    networks:
      - ml_net

  model:
    build: ./model
    ports:
      - "5002:5000"
    networks:
      - ml_net

  postprocess:
    build: ./postprocess
    ports:
      - "5003:5000"
    depends_on:
      - preprocess
    networks:
      - ml_net

networks:
  ml_net:
    driver: bridge
